version: "3.8"
services:
  laravel:
    container_name: laravel-app
    restart: always
    build:
      context: ./server/rest
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kaizenklassv3 # Match this with the db service
      DB_USERNAME: kaizenklass # Match with MYSQL_USER in db service
      DB_PASSWORD: secret # Match with MYSQL_PASSWORD in db service
    depends_on:
      - db
    networks:
      - app-network

  remix:
    container_name: remix-app
    restart: always
    build:
      context: ./client/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/web:/app
    depends_on:
      - laravel
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: kaizenklassv3 # Ensure this matches laravel service
      MYSQL_USER: kaizenklass
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
