version: "3.8"
services:
  # Laravel server
  laravel:
    container_name: laravel-app
    restart: always
    build:
      context: ./server/rest
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kaizenklassv3
      DB_USERNAME: root
      DB_PASSWORD: 12345
    depends_on:
      - db
    networks:
      - app-network

  # Remix frontend
  remix:
    container_name: remix-app
    restart: always
    build:
      context: ./client/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/web:/app
    depends_on:
      - laravel
    networks:
      - app-network

  # MySQL database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kaizenklass
      MYSQL_USER: kaizenklass
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

